[package]
name = "preety_output-error"
version = "0.1.0"
authors = ["Josh7GAS <joshuaandre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.7"
exitfailure = "0.5.1"